{% set version = "2.0.35" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-epir
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/epiR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/epiR/epiR_{{ version }}.tar.gz
  sha256: a85741b7a26e39e80552222e0bdb0f843de130fae18bf3bf5af7cc5d73116574

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-biasedurn
    - r-lubridate
    - r-pander
    - r-survival
  run:
    - r-base
    - r-biasedurn
    - r-lubridate
    - r-pander
    - r-survival

test:
  commands:
    - $R -e "library('epiR')"           # [not win]
    - "\"%R%\" -e \"library('epiR')\""  # [win]

about:
  home: https://fvas.unimelb.edu.au/research/groups/veterinary-epidemiology-melbourne
  license: GPL-2.0-or-later
  summary: Tools for the analysis of epidemiological data. Contains functions for directly and indirectly adjusting measures of disease frequency, quantifying measures of association on the basis of single or multiple strata of count data presented in a contingency table, and computing confidence intervals around incidence
    risk and incidence rate estimates. Miscellaneous functions for use in meta-analysis, diagnostic test interpretation, and sample size calculations.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: epiR
# Version: 1.0-15
# Date: 2020-06-13
# Title: Tools for the Analysis of Epidemiological Data
# Author: Mark Stevenson <mark.stevenson1@unimelb.edu.au> with contributions from Telmo Nunes, Cord Heuer, Jonathon Marshall, Javier Sanchez, Ron Thornton, Jeno Reiczigel, Jim Robison-Cox, Paola Sebastiani, Peter Solymos, Kazuki Yoshida, Geoff Jones, Sarah Pirikahu, Simon Firestone, Ryan Kyle, Johann Popp, Mathew Jay and Charles Reynard.
# Maintainer: Mark Stevenson <mark.stevenson1@unimelb.edu.au>
# Description: Tools for the analysis of epidemiological data. Contains functions for directly and indirectly adjusting measures of disease frequency, quantifying measures of association on the basis of single or multiple strata of count data presented in a contingency table, and computing confidence intervals around incidence risk and incidence rate estimates. Miscellaneous functions for use in meta-analysis, diagnostic test interpretation, and sample size calculations.
# Depends: R (>= 3.0.0), survival
# Imports: BiasedUrn, methods
# Suggests: MASS (>= 3.1-20), knitr, rmarkdown, RColorBrewer, ggplot2, plyr, rgdal, scales, spData, spatstat, foreign, maptools, rgeos, mapproj
# VignetteBuilder: knitr
# License: GPL (>= 2)
# Packaged: 2020-06-13 09:02:04 UTC; Mark Stevenson
# URL: https://fvas.unimelb.edu.au/research/groups/veterinary-epidemiology-melbourne
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2020-06-14 14:30:07 UTC
